name: Ubuntu
on:
  watch:
    types: [started]
jobs:
  Ubuntu:
    runs-on: macos-latest
    steps:
    - name: SSH connection to Actions
      uses: csexton/debugger-action@master
      #uses: Ryan-Ng/debugger-action@master
